on: [workflow_dispatch, push]

# will this be triggered when I commit to main branch?

# well the answer is no

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I'm a on branch1!"
        shell: bash
